# Generated by Django 3.2.12 on 2022-03-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreid', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_genre',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'db_member',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('poster', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=50)),
                ('open_date', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
                ('running_time', models.IntegerField()),
                ('director', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=200)),
                ('open_country', models.CharField(max_length=20)),
                ('trailer', models.CharField(max_length=500, null=True)),
                ('summary', models.CharField(max_length=2000)),
                ('genreid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genreid', to='web.genre')),
            ],
            options={
                'db_table': 'db_movie',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.FloatField(default=0)),
                ('movieid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_movieid', to='web.movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_userid', to='web.member')),
            ],
            options={
                'db_table': 'db_review',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('boardid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('read_count', models.IntegerField(default=0)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_movieid', to='web.movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_userid', to='web.member')),
            ],
            options={
                'db_table': 'db_board',
            },
        ),
    ]
