# Generated by Django 3.2.12 on 2022-03-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_board_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='movieid',
        ),
    ]
