# Generated by Django 3.2.12 on 2022-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_board_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
