# Generated by Django 3.2.12 on 2022-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_board_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='checka',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='checkq',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
