# Generated by Django 4.0.2 on 2022-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='voter',
            field=models.ManyToManyField(related_name='voter_userid', to='web.Member'),
        ),
    ]
