# Generated by Django 4.0.2 on 2022-03-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_review_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reviewid', models.CharField(max_length=30)),
                ('memberid', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_voter',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='voter',
        ),
    ]
