# Generated by Django 4.0.2 on 2022-03-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_voter_score_alter_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_vote', to='web.voter'),
        ),
    ]
