# Generated by Django 4.0.2 on 2022-03-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_review_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='score',
            new_name='recommend',
        ),
    ]
